baseURL = "https://nitishpuri.gitlab.io"
languageCode = "en-us"
title = "Code/Art - Nitish Puri"
# theme = "mytheme"
theme = "hugo-bootstrap-5"
relativeURLS = true

[params]
author = "Nitish Puri"
description = "These are some notes."
logo = "https://www.mywebsite.com/images/logo.png"
images = ["/images/site-feature-image.jpg"]

[taxonomies]
  tag = "tags"
  category = "categories"


# Google analytics
googleAnalytics = "G-52F9VYD18Q"

enableRobotsTXT = true
  
[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":fileModTime", ":default"]

sectionPagesMenu = "main"
